version: "3.8"
services:
  app:
    build: ./architecture/php
    volumes:
    - ./backend:/work

  web:
    image: nginx:1.18-alpine
    ports:
      - 10080:80
    volumes:
      - ./backend:/work
      - ./architecture/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /work